# Generated by Django 4.1.3 on 2023-04-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('card_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('card_holder_name', models.CharField(max_length=50)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
